travis:
  secure:
    BINSTAR_TOKEN: YA38TBE1PYp0LKNFs3nrRtBPAZUn5fYtUbWW901JCdS0O8t2jK2iY1P7PjKNw+eB4wrCnUuF+ZTALYZGK89Ou2XdCF+VvOveGQjDDpqyK4gvOaXZX6mqDhFMHlnSIeYMaNiU7Ocqd9VSTWEXAhpW4LrWIqvEraB/NCOmgiJVTjol3glnYyzqQu4/6wkoGjAzokuEDL+qYW54GjIoiuisshUsEXFe/btQ1Duf/U+nVG0J3Ndu9VpP4VCkkbfWlCyGkhbe8cvmETrX6FMACkaImjxsqOconc5YJ7dnr5ITaDK1h25k34l65J5XfJX3y2tk3GwAz0obQJ+XDL+EeKZQPVCzn8sm13Mdpt1kBL/JJVvdkEp2Tr643ZYauqTcjBfEyB/5Ipa9L8JpJTYZUAoQMXuntyl5gJ+rytf5ZlcFU3gxYaOJqzxnjMfpx5uhe6vCI7T2LP/eJpBH+u35M4THO9PF4kBAkO1mLdY9T+Eev7Kin+J8kajiVKk42n1wx4utSh14e9oWlYdz8nznp3MSL2joRv1RkaKmlhTIrOWt4Irb0i77KrmTwC44MEUjEXTdvFOQrGEOnTjY9+Wzt5DgR3HHnZy6JeJRLi+9KJSSKAAGkERtUh4oTFX3XXrFtrnzBq4u3vU/haVG7FlM3T21LpGWj2yJOdmgHX/dva1DP4U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
