travis:
  secure:
    BINSTAR_TOKEN: wEB+DNDzwypj1niTkcdYw+vJ0IVd2+7Ux9G2fWEG9bWV2e55kjCz47mg4SGqeM7/WdwNKOdggfQ6tXv/CHoTSAO4p4p3uixbgjoIoWVuwLxK4Tkifd3F1fZGM3ahqjSgIU3wwRP61tBXbnMJx+V+cJHgpJANBODzxQ3gVERq7PW1kl3+WVBN843cnICwGl7yer23lpbvbqnTjtc++2IFRHHmCRWx8OWXLykrDxrprV2CCT1dELFhZ8VrWPqIMbVAqWJVWP9nsQrla6nu5uu8OwIluE7VoTfeZIfFGqQvN2/nBsH3KV0YoJbTW7oyQALYo9IvSkoKB2THBYVIlqaJDzctUv0M3dt5v3b9RgnrlYYhx1EqxLkqtr1DzE7aE45hO/8hf8H4lGfXQiRJiTJcoCr4eM7sV6U5orvx2sBDsxpU9AOwOtcimFcF1vUYilr4dTxoEiNyQcd4n+DBElz3E5qloV1coWXTBJm5JfOQ+PHkLVUjbuznHVzBWExyPhRK934OhaJ94FOJ4t2H3XzsoVMbgik1qQZ7ewFPU+QKUkXm1eS8ePb/Wa9J5H/UKSPPeS5e2sH5px5T+4jtzRqwuof8sRDA+1snK1RdMBEmeQnirBK6uGKkm+D6+jPqqAhZkOh7i6Pfz4C5ynmuox9z5p2nyTSQa/Y5VCpxQBb3EIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
